apiVersion: batch/v1
kind: Job
metadata:
  name: wordpress-init-job
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  ttlSecondsAfterFinished: 100
  backoffLimit: 10
  template:
    spec:
      securityContext:
        runAsUser: {{ .Values.wordpress.job.uid }}
        runAsGroup: {{ .Values.wordpress.job.gid }}
        fsGroup: {{ .Values.wordpress.job.gid }}
      containers:
        - name: "{{ .Release.Name }}-job"
          image: {{ .Values.wordpress.job.image }}
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - |
              # Wait for MariaDB
              attempt=1
              max_attempts=10




              until mariadb-admin ping -h{{ .Release.Name }}-mariadb -u${WORDPRESS_DB_USER} -p${WORDPRESS_DB_PASSWORD}; do
                if [ $attempt -eq $max_attempts ]; then
                  echo "MariaDB connection failed after $max_attempts attempts"
                  exit 1
                fi
                echo "Attempt $attempt: MariaDB not ready, waiting 20s..."
                sleep 20
                attempt=$((attempt + 1))
              done

              # Clone custom plugins repository
              echo "Cloning custom wordpress repository..."
              echo "Using repo: {{ .Values.github.wp_repo }} commit: {{ .Values.github.commit }}"

              if ! git clone https://${GIT_TOKEN}@github.com/{{ .Values.github.wp_repo }}.git $REPO_LOCATION; then
                echo "Failed to clone repository"
                exit 60
              fi

              cd $REPO_LOCATION
              if ! git checkout {{ .Values.github.commit }}; then
                echo "Failed to checkout commit"
                exit 61
              fi

              cd /var/www/html
              # Execute the installation script
              wordpress/scripts/plugin_install.sh
          env:
            - name: GIT_TERMINAL_PROMPT
              value: "0"
            - name: TEMP_DIR
              value: /wordpress
            - name: REPO_LOCATION
              value: /wordpress/repo
          envFrom:
            - secretRef:
                name: "{{ .Release.Name }}-secrets"
            - secretRef:
                name: "{{ .Release.Name }}-github-secret"
          volumeMounts:
            - name: wordpress-storage
              mountPath: /var/www/html
            - name: temp-dir
              mountPath: /wordpress
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-pvc"
        - name: temp-dir
          emptyDir: {}
      restartPolicy: OnFailure
