---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-github-secret
  labels:
    {{ include "wordpress.labels" . | nindent 4 }}
type: Opaque
stringData:
  GIT_TOKEN: {{ .Values.github.token | default "$(GITHUB_TOKEN)" }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    {{ include "wordpress.labels" . | nindent 4 }}
type: Opaque
data:
  WORDPRESS_DB_HOST: {{ printf "%s-mariadb" .Release.Name | b64enc | quote }}
  WORDPRESS_DB_USER: {{ .Values.mariadb.auth.username | b64enc | quote }}
  WORDPRESS_DB_PASSWORD: {{ .Values.mariadb.auth.password | b64enc | quote }}
  WORDPRESS_DB_NAME: {{ .Values.mariadb.auth.database | b64enc | quote }}

  WORDPRESS_URL: {{ printf "https://%s" (index .Values.wordpress.ingress.hosts 0).host | b64enc | quote }}
  WORDPRESS_TITLE: {{ .Values.wordpress.siteTitle | b64enc | quote }}
  WORDPRESS_ADMIN_USER: {{ .Values.wordpress.adminUser | b64enc | quote }}
  WORDPRESS_ADMIN_PASSWORD: {{ .Values.wordpress.adminPassword | b64enc | quote }}
  WORDPRESS_ADMIN_EMAIL: {{ .Values.wordpress.adminEmail | b64enc | quote }}


