apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
  labels:
    {{ include "wordpress.labels" . | nindent 4 }}
spec:
  type: {{ .Values.wordpress.service.type | default "ClusterIP" }}
  ports:
    - port: {{ include "wordpress.service.port" . }}

      targetPort: http
      {{- if eq .Values.wordpress.service.type "NodePort" }}
      nodePort: {{ .Values.wordpress.service.nodePort | default "null" }}
      {{- end }}
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
